In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Raw_Dataset - Sheet1.csv')

In [3]:
# Anzhelika = data.loc[:250, 'Գիրք 1':] #SER
# Anzhelika.to_csv("Anzhelika.csv")

In [4]:
# Diana = data.loc[250:500, 'Գիրք 1':]
# Diana.to_csv("Diana.csv")

In [5]:
# Anzhela = data.loc[500:750, 'Գիրք 1':]
# Anzhela.to_csv("Anzhela_2.csv")

In [6]:
Armen = data.loc[750:, 'Գիրք 1':].reset_index()

In [7]:
Armen.columns

Index(['index', 'Գիրք 1', 'Գիրք 2', 'Գիրք 3', 'Գիրք 4', 'Գիրք 5', 'Գիրք 6',
       'Գիրք 7', 'Գիրք 8', 'Գիրք 9', 'Գիրք 10', '_Գիրք 1_', '_Գիրք 2_',
       '_Գիրք 3_', '_Գիրք 4_', '_Գիրք 5_', '_Գիրք 6_', '_Գիրք 7_', '_Գիրք 8_',
       '_Գիրք 9_', '_Գիրք 10_', 'Հեղինակ 1', 'Հեղինակ 2', 'Հեղինակ 3',
       'Հեղինակ 4', 'Հեղինակ 5', 'Հեղինակ 6', 'Հեղինակ 7', 'Հեղինակ 8',
       'Հեղինակ 9', 'Հեղինակ 10'],
      dtype='object')

In [8]:
def remove_symbols(sentence):
    if(sentence == np.nan):
        return (np.nan)
    sentence = str(sentence)
    sentence = sentence.strip()
    new_sentence = ""
    for symbol in sentence:
        if symbol.isalpha() or symbol == " ":
            new_sentence += symbol
    return (new_sentence)

In [9]:
Armen.head(1)

,index,Գիրք 1,Գիրք 2,Գիրք 3,Գիրք 4,Գիրք 5,Գիրք 6,Գիրք 7,Գիրք 8,Գիրք 9,...,Հեղինակ 1,Հեղինակ 2,Հեղինակ 3,Հեղինակ 4,Հեղինակ 5,Հեղինակ 6,Հեղինակ 7,Հեղինակ 8,Հեղինակ 9,Հեղինակ 10
0,750,Շ. Բրոնտե <>,Վ. Պետրոսյան << Վերջին ուսուցիչը>>,Էքզյուպերի <>,Ջ. Գրին <>,Պ. Կոելու <>,Շ. Ազնավուր <>,NaN,NaN,NaN,...,Շարլոթ Բրոնտե,Պաուլու Կոելու,Վարդգես Պետրոսյան,Շառլ Ազնավուր,Ջոն Գրին,Ագաթա Քրիստի,Ռեմարկ,NaN,NaN,NaN

In [10]:
data = data.applymap(remove_symbols)
data = data.applymap(lambda string: string.lower())

In [11]:
authors_data = data.loc[:, 'Հեղինակ 1' : 'Հեղինակ 10']
arr = authors_data.values.flatten()

In [12]:
authors_series = pd.Series(arr).value_counts()
authors_series = authors_series.iloc[1:]
authors_series = authors_series[authors_series > 2]
authors_series

պարույր սևակ           191
շիրվանզադե             186
վարդգես պետրոսյան      177
ջոն գրին               121
րաֆֆի                  112
                      ...
եչարենց                  3
նաիրի զարյան             3
лермонтов                3
ալ դյումա                3
գաբրիել սունդուկյան      3
Length: 264, dtype: int64

In [13]:
def jaccard_distance(s, t):
    set_s = set(s)
    set_t = set(t)
    return len(set_s.intersection(set_t)) / len(set_s.union(set_t))

# Example usage
s1 = "պարույր սևակ".lower()
s2 = "օսկար ուայլդ".lower()
distance = jaccard_distance(s1, s2)
print(distance) # Output: 0.5

0.6153846153846154

In [14]:
author_names = pd.Series(authors_series.index)

In [15]:
author_names

0             պարույր սևակ
1               շիրվանզադե
2        վարդգես պետրոսյան
3                 ջոն գրին
4                    րաֆֆի
              ...
259                եչարենց
260           նաիրի զարյան
261              лермонтов
262              ալ դյումա
263    գաբրիել սունդուկյան
Length: 264, dtype: object

In [16]:
frequent_names = author_names.apply(lambda name: jaccard_distance(name, "պարույր սևակ")).sort_values(ascending=False).head(10).index

In [17]:
author_names.iloc[frequent_names]

0         պարույր սևակ
242       պարյուր սևակ
175      պարույր սեւակ
17        օսկար ուայլդ
86              պ սևակ
33     պաուլու կոելյու
95      պաուլո կուելյո
98          հուսիկ արա
172      պաուլո կոեյլո
70      պաուլո կոելյու
dtype: object

zsh:1: command not found: conda

In [12]:
!pip install levenshtein

zsh:1: command not found: python

In [9]:
import Levenshtein

ModuleNotFoundError: No module named 'Levenshtein'

In [28]:
Armen = Armen.applymap(remove_symbols)
Armen = Armen.applymap(lambda string: string.lower())

In [29]:
Armen.head()

,index,Գիրք 1,Գիրք 2,Գիրք 3,Գիրք 4,Գիրք 5,Գիրք 6,Գիրք 7,Գիրք 8,Գիրք 9,...,Հեղինակ 1,Հեղինակ 2,Հեղինակ 3,Հեղինակ 4,Հեղինակ 5,Հեղինակ 6,Հեղինակ 7,Հեղինակ 8,Հեղինակ 9,Հեղինակ 10
0,,շ բրոնտե,վ պետրոսյան վերջին ուսուցիչը,էքզյուպերի,ջ գրին,պ կոելու,շ ազնավուր,nan,nan,nan,...,շարլոթ բրոնտե,պաուլու կոելու,վարդգես պետրոսյան,շառլ ազնավուր,ջոն գրին,ագաթա քրիստի,ռեմարկ,nan,nan,nan
1,,ջեյն էյի,մոլեռանդ հողմերի դարավանդը,աննա կարենինա ալքիմիկոսը,նախօրեին եթե որոտանը խոսեր,ջոնաթան լիվինգսթոն անունով ճայը,ծաղիկներ էլջերնոնի համար,հպարտություն և նախապաշարմունք,այնտեղ որտեզ ծաղկում են վայրի վարդեր,ես մինչ քեզ հայրիկ դու խենթ ես,...,շառլոթ բրոնտե էմիլի բրոնտե,ջեյն օսթին մարկես,պարույր սևակ,շիրվանզադե թումանյան,աննա թոդ,տուրգենև,շեքսպիր,վիլյամ սարոյան դդեմիրճյան,համո սահյան վահան տերյան,սերգեյ եսենին անահիտ սեկոյան
2,,ալեքսանդր դյումա կոմս մոնտե քրիստո,շառլոթ բրոնտե ջեյնէյր,դերենիկ դեմիրճյան վարդանանք,րաֆֆի խենթը,շիրվանզադե նամուսպատվի համար,ջոն գրին աստղերն են մեղավոր,փոթորկից առաջ,անուշավան պողոսյան սեր մի խաղա,հեկտոր մալո առանց ընտանիքի,...,ալեքսանդր դյումա,շառլոտ բրոնտե,լևոն շանթ,nan,nan,nan,nan,nan,nan,nan
3,,վարդգես պետրոսյան,պաուլո կոելյու,հեղինակը չեմ հիշում,ջոջո մոյես,,nan,nan,,նարդոս,...,պարույր սևակ,հովհաննես թումանյան,ալեքսանդր շիրվանզադե,մուրացան,պաուլո կոելյու,նարդոս,nan,nan,nan,nan
4,,ես և նա,մի սիրո պատմություն,հարրի փոթերի բոլոր մասերը,nan,nan,nan,nan,nan,nan,...,հիմնականում արտասահմանյան գրողների եմ նախընտրում,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [30]:
import random

def random_choice(key, probability_of_val1):
    return key if random.random() < probability_of_val1 else 0

wordDict = {
    "ց": {"c": 0.8, "ts": 0.2},
    "ր": {"r": 1},
    "փ": {"p": 1},
    "օ": {"o": 1},
    "ք": {"q": 0.7, "k": 0.3},
    "և": {"ev": 0.7, "yev": 0.3},
    "ֆ": {"f": 1},
    "ՈՒ": {"U": 1},
    "Ու": {"U": 1},
    "ու": {"u": 1},
    "Ա": {"A": 1},
    "Գ": {"G": 1},
    "Բ": {"B": 1},
    "Ե": {"Ye": 0.1, "YE": 0.1, "E": 0.8},
    "Դ": {"D": 1},
    "Է": {"E": 1},
    "Զ": {"Z": 1},
    "Թ": {"T": 0.9, "Th": 0.05, "TH": 0.05},
    "Ը": {"Y": 0.35, "@": 0.45, "E": 0.2},
    "Ի": {"I": 1},
    "Ժ": {"ZH": 0.15, "J": 0.5, "Zh": 0.15, "G": 0.2},
    "Խ": {"Gh": 0.05, "X": 0.7, "Kh": 0.1, "KH": 0.1, "GH": 0.05},
    "Լ": {"L": 1},
    "Կ": {"K": 1},
    "Ծ": {"C": 0.3, "&": 0.1, "TS": 0.3, "Ts": 0.3},
    "Ձ": {"Dz": 0.4, "Z": 0.1, "DZ": 0.4, "D": 0.1},
    "Հ": {"H": 1},
    "Ճ": {"CH": 0.2, "Ch": 0.2, "J": 0.4, "Tch": 0.1, "C": 0.1},
    "Ղ": {"X": 0.5, "Gh": 0.25, "GH": 0.25},
    "Յ": {"Y": 0.9, "J": 0.1},
    "Մ": {"M": 1},
    "Շ": {"SH": 0.4, "Sh": 0.4, "S": 0.2},
    "Ն": {"N": 1},
    "Չ": {"4": 0.2, "CH": 0.3, "Ch": 0.4, "C": 0.1},
    "Ո": {"O": 1},
    "Ջ": {"Dj": 0.05, "J": 0.6, "DJ": 0.05, "G": 0.3},
    "Պ": {"P": 1},
    "Ս": {"S": 1},
    "Ռ": {"R": 1},
    "Տ": {"T": 1},
    "Վ": {"V": 1},
    "Ց": {"C": 0.8, "TS": 0.1, "Ts": 0.1},
    "Ր": {"R": 1},
    "Փ": {"P": 1},
    "Ւ": {"V": 1},
    "Օ": {"O": 1},
    "Ք": {"Q": 0.7, "K": 0.3},
    "Ֆ": {"F": 1},
    "ա": {"a": 1},
    "գ": {"g": 1},
    "բ": {"b": 1},
    "ե": {"ye": 0.2, "e": 0.8},
    "դ": {"d": 1},
    "է": {"e": 1},
    "զ": {"z": 1},
    "թ": {"t": 0.9, "th": 0.1},
    "ը": {"y": 0.35, "@": 0.45, "e": 0.2},
    "ի": {"i": 1},
    "ժ": {"j": 0.5, "zh": 0.3, "g": 0.2},
    "խ": {"x": 0.7, "kh": 0.2, "gh": 0.1},
    "լ": {"l": 1},
    "կ": {"k": 1},
    "ծ": {"c": 0.3, "ts": 0.6, "&": 0.1},
    "ձ": {"z": 0.1, "dz": 0.8, "d": 0.1},
    "հ": {"h": 1},
    "ճ": {"ch": 0.4, "c": 0.1, "j": 0.4, "tch": 0.1},
    "ղ": {"x": 0.5, "gh": 0.5},
    "յ": {"y": 0.9, "j": 0.1},
    "մ": {"m": 1},
    "շ": {"sh": 0.8, "s": 0.2},
    "ն": {"n": 1},
    "չ": {"4": 0.2, "ch": 0.7, "c": 0.1},
    "ո": {"o": 1},
    "ջ": {"j": 0.6, "dj": 0.1, "g": 0.3},
    "պ": {"p": 1},
    "ս": {"s": 1},
    "ռ": {"r": 1},
    "տ": {"t": 1},
    "վ": {"v": 1},
    "ւ": {"v": 1},
}
def multipleReplace(text):
    second_key = " "
    mod_text = list(text)
    letter = 0;
    while letter != len(mod_text):       
        for (key, another_dict) in wordDict.items():
            try:
                if (mod_text[letter] == 'ո' and mod_text[letter+1] == 'ւ'):
                    mod_text = mod_text[:letter]+ ['u']+ mod_text[letter+2:]
                    break;
            except IndexError:
                break

            try:
                if(mod_text[letter] == 'Ո' and mod_text[letter+1] == 'Ւ'):
                    mod_text = mod_text[:letter]+ ['U']+ mod_text[letter+2:]
                    break;
            except IndexError:
                break
            if (mod_text[letter] == key):
                while(mod_text[letter] != second_key):     
                    for (second_key, value) in another_dict.items():
                        if (random_choice(second_key, value)):
                            mod_text[letter] = second_key                                
                            break;
            if (mod_text[letter] == second_key):
                break 
        letter += 1;
    return ''.join(mod_text)

In [31]:
multipleReplace("ԻՄ ԱՆՈՒՆԸ ԿԱՌԼեոն Է, դոն կառլեոնե")

'IM ANUNE KARLeon E, don karleone'

In [32]:
wordDict_2 = {
    "zh": {"ժ" : 1},
    "ch": {"չ" : 0.8, "ճ" : 0.2},
    "ts" : {"ծ" : 1},
    "c": {"ծ" : 0.5, "ց" : 0.4, "չ" : 0.1},
    "ev": {"և": 1},
    "ye": {"ե": 1},
    "th": {"թ" : 1},
    "kh": {"խ" : 1},
    "gh": {"ղ" : 1},
    "dz": {"ձ" : 1},
    "sh": {"շ" : 1},
    "vo" : {"ո" : 1},
    "dj" : {"ջ" : 1},
    "r" : {"ր" : 0.9, "ռ" : 0.1},
    "p": {"պ": 0.8, "փ": 0.2},
    "o": {"ո": 0.7, "օ" : 0.3},
    "q": {"ք": 1},
    "k": {"կ": 1},
    "f": {"ֆ": 1},
    "u": {"ու": 1},
    "a": {"ա": 1},
    "g": {"գ": 1},
    "b": {"բ": 1},
    "e": {"ե" : 0.7, "է" : 0.3},
    "d": {"դ": 1},
    "z": {"զ": 1},
    "t": {"տ" : 0.6, "թ": 0.4},
    "y" : {"յ" : 0.6, "ը" : 0.4},
    "@": {"ը" : 1},
    "i": {"ի": 1},
    "j": {"ջ" : 0.6, "ճ" : 0.2, "ժ" : 0.2},
    "x": {"խ" : 1},
    "l" : {"լ" : 1},
    "k": {"կ": 1},
    "h": {"հ": 1},
    "m": {"մ": 1},
    "n": {"ն": 1},
    "s": {"ս": 1},
    "v": {"վ": 1},
}
def reverseMultipleReplace(text):
    #looping through single letter
    def loop(mod_text, letter, second_key):
        while(mod_text[letter] != second_key):     
            for (second_key, value) in another_dict.items():
                if (random_choice(second_key, value)):
                    mod_text[letter] = second_key
                    break;
    second_key = " "
    mod_text = list(text)
    letter = 0;
    while letter != len(mod_text):       
        for (key, another_dict) in wordDict_2.items():
            if (letter != len(mod_text) - 1):
                #For the cases with 2 letters
                if (mod_text[letter] + mod_text[letter+1] == key):
                    while((mod_text[letter] + mod_text[letter+1]) != second_key):     
                        for (second_key, value) in another_dict.items():
                            if (random_choice(second_key, value)):
                                mod_text[letter] = second_key
                                mod_text = mod_text[:letter+1] + mod_text[letter+2:]
                                second_key = mod_text[letter]
                                break;
                        if (mod_text[letter] == second_key):
                            break
                #For the case of a 1 letter
                elif (mod_text[letter] == key):
                    loop(mod_text, letter, second_key)
            else:
                if (mod_text[letter] == key):
                    loop(mod_text, letter, second_key)
            if (mod_text[letter] == second_key):
                break
        letter += 1;
    return ''.join(mod_text)

In [33]:
#for i in range(100):
#    print(reverseMultipleReplace("Totovenc".lower()))

In [34]:
sample = Armen.iloc[248:, :]
sample

,index,Գիրք 1,Գիրք 2,Գիրք 3,Գիրք 4,Գիրք 5,Գիրք 6,Գիրք 7,Գիրք 8,Գիրք 9,...,Հեղինակ 1,Հեղինակ 2,Հեղինակ 3,Հեղինակ 4,Հեղինակ 5,Հեղինակ 6,Հեղինակ 7,Հեղինակ 8,Հեղինակ 9,Հեղինակ 10
248,,nardos patmvacqner,dprocakan tariner,caxkac pshalarer,hovhannes tumanyan patmvacqner,nan,nan,nan,nan,nan,...,hovhannes tumanyan,nardos,avetiq isahakyan,hamo sahyan,daniel varujan,nan,nan,nan,nan,nan
249,,պարույր սևակ,համո սահյան,nan,nan,nan,nan,nan,nan,nan,...,պարույր սևակ,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [35]:
import re

def convert_to_armenian(word):
    if(re.search('[a-zA-Z]', word) != None and word == np.nan):
        return word
    return(reverseMultipleReplace(word))

In [36]:
sample.applymap(convert_to_armenian)

,index,Գիրք 1,Գիրք 2,Գիրք 3,Գիրք 4,Գիրք 5,Գիրք 6,Գիրք 7,Գիրք 8,Գիրք 9,...,Հեղինակ 1,Հեղինակ 2,Հեղինակ 3,Հեղինակ 4,Հեղինակ 5,Հեղինակ 6,Հեղինակ 7,Հեղինակ 8,Հեղինակ 9,Հեղինակ 10
248,,նարդոս պատմվացքներ,դպրոցական տարիներ,ցախկած պշալարեր,հովհաննես թումանըան պաթմվածքներ,նան,նան,նան,նան,նան,...,հովհաննես տումանյան,նարդոս,ավեթիք իսահակյան,համո սահյան,դանիել վարուջան,նան,նան,նան,նան,նան
249,,պարույր սևակ,համո սահյան,նան,նան,նան,նան,նան,նան,նան,...,պարույր սևակ,նան,նան,նան,նան,նան,նան,նան,նան,նան

In [15]:
def jaccard_distance(s, t):
    set_s = set(s)
    set_t = set(t)
    return len(set_s.intersection(set_t)) / len(set_s.union(set_t))

# Example usage
s1 = "հովհաննես թումանյան".lower()
s2 = "հովհաննես տումանյան".lower()
distance = jaccard_distance(s1, s2)
print(distance) # Output: 0.5

0.8461538461538461